### ISSUE TITLE
Update DevSite Site to Gatsby v3.8

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1422]
Due to the Gatsby Cloud bug  being resolved in this Gatsby issue(https://github.com/gatsbyjs/gatsby/issues/32042) we'll need to bump our version of Gatsby to [v3.8](https://www.gatsbyjs.com/docs/reference/release-notes/v3.8/)

### Acceptance Criteria 

- [x] Upgrade site to Gatsby v3.8
- [x] Update other Gatsby Packages see this [PR for examples](https://github.com/newrelic/docs-website/pull/2911/files) run `yarn upgrade-interactive --latest`
- [x] Test site visually 
- [x] Fix console log error #1448 
- [x] Fix other terminal errors - TBD
- [x] Test if a PR builds 

### Bug

PRs fail to build on Gatsby Cloud sites that don't have  `gatsby 3.8` or is  using `gatsby-plugin-gatsby-cloud@2.8.1`

<img width="1030" alt="Screen Shot 2021-06-22 at 4 00 31 PM" src="https://user-images.githubusercontent.com/1395158/123172729-c7c99280-d43a-11eb-8fde-6c2fb4a3331f.png">

**Comment by jpvajda** [comment]
I ran into a couple weird things in the terminal after running `yarn start`


```
{
  param: [
    { type: 'React.MouseEvent', name: 'event', description: '' },
    {
      type: 'number',
      name: 'value',
      description: 'Id of the account selected.'
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'function',
      name: 'mutate',
      description: 'Function to trigger a mutation from your UI.'
    },
    {
      type: 'MutationResult',
      name: 'mutationResult',
      description: 'Results of the\n        mutation.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
⠀
{}
{}
{}
{}
{}
{}
{}
⠀
{}
{}
{}
{}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
⠀
{}
{}
{}
{}
{}
{
  param: [
    {
      type: 'React.ChangeEvent',
      name: 'event',
      description: 'The event source of the callback.\n' +
        '        You can access the new value with `event.target.checked`.'
    }
  ]
}
⠀
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [ { type: 'Cursor', name: 'cursor', description: 'Items to load.' } ],
  examples: [
    {
      label: 'Lazy loading items',
      options: [Object],
      sourceCode: "import { Dropdown, DropdownItem } from 'nr1';\n" +
        '\n' +
        '// This example assumes you have a way to know/load this information.\n' +
        'const remoteTotalNumberOfItems = 9000;\n' +
        'const items = [\n' +
        "  { id: 1, text: 'Item 1' },\n" +
        "  { id: 2, text: 'Item 2' },\n" +
        "  { id: 3, text: 'Item 3' },\n" +
        "  { id: 4, text: 'Item 4' },\n" +
        '];\n' +
        '\n' +
        'function fetchMore({ startIndex, stopIndex }) {\n' +
        '  return fetch(\n' +
        '    `path/to/api?startIndex=${startIndex}&stopIndex=${stopIndex}`,\n' +
        '  ).then((response) => {\n' +
        '    // Store items in item list...\n' +
        '  });\n' +
        '}\n' +
        '\n' +
        'const dropdown = (\n' +
        '  <Dropdown\n' +
        '    items={items}\n' +
        '    onLoadMore={fetchMore}\n' +
        '    rowCount={remoteTotalNumberOfItems}\n' +
        '    title="Dropdown"\n' +
        '  >\n' +
        '    {({ item, index }) => <DropdownItem key={index}>{item.text}</DropdownItem>}\n' +
        '  </Dropdown>\n' +
        ');'
    },
    {
      label: 'Integration with the query components',
      options: [Object],
      sourceCode: "import { EntitiesByDomainTypeQuery, Dropdown, DropdownItem } from 'nr1';\n" +
        '\n' +
        'const renderDropdown = (queryResult) => {\n' +
        '  const { fetchMore, loading, data } = queryResult;\n' +
        '  const { results, count } = data.actor.entitySearch;\n' +
        '\n' +
        '  return (\n' +
        '    <Dropdown\n' +
        '      items={results.entities}\n' +
        '      onLoadMore={fetchMore}\n' +
        '      rowCount={count}\n' +
        '      title="Dropdown"\n' +
        '    >\n' +
        '      {({ item, index }) => (\n' +
        '        <DropdownItem key={index}>{item.text}</DropdownItem>\n' +
        '      )}\n' +
        '    </Dropdown>\n' +
        '  );\n' +
        '};\n' +
        '\n' +
        'const style = { width: 200, height: 300 };\n' +
        'const dropdown = (\n' +
        '  <EntitiesByDomainTypeQuery entityDomain="APM" entityType="APPLICATION">\n' +
        '    {renderDropdown}\n' +
        '  </EntitiesByDomainTypeQuery>\n' +
        ');'
    }
  ]
}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [ { type: 'React.ChangeEvent', name: 'event', description: '' } ]
}
{
  param: [
    { type: 'React.MouseEvent', name: 'event', description: '' },
    { type: 'boolean', name: 'opened', description: '' }
  ]
}
⠀
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
⠀
{
  param: [ { type: 'Cursor', name: 'cursor', description: 'Items to load.' } ]
}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'function',
      name: 'mutate',
      description: 'Function to trigger a mutation from your UI.'
    },
    {
      type: 'MutationResult',
      name: 'mutationResult',
      description: 'Results of the\n        mutation.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [
    { type: 'React.MouseEvent', name: 'event', description: '' },
    { type: 'boolean', name: 'checked', description: '' }
  ]
}
{}
{}
⠀
{}
{}
⠀
{}
{}
{}
{}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
⠀
{}
{}
{}
{}
{}
{}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
⠀
{
  param: [ { type: 'Cursor', name: 'cursor', description: 'Items to load.' } ]
}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{}
{
  examples: [
    {
      label: 'Example 1',
      options: [Object],
      sourceCode: 'function render() {\n' +
        '  <>\n' +
        '    {this.state.mounted && (\n' +
        '      <Modal\n' +
        '        hidden={this.state.hidden}\n' +
        '        onHideEnd={() => this.setState({ mounted: false })}\n' +
        '        onClose={() => this.setState({ hidden: true })}\n' +
        '      >\n' +
        '        <h1>Modal</h1>\n' +
        '        <p>\n' +
        '          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do\n' +
        '          eiusmod tempor incididunt ut labore et dolore magna aliqua.\n' +
        '        </p>\n' +
        '      </Modal>\n' +
        '    )}\n' +
        '  </>;\n' +
        '}'
    }
  ]
}
{}
{}
{}
{
  param: [
    {
      type: 'React.FocusEvent',
      name: 'event',
      description: 'Event source of the callback.'
    }
  ]
}
{
  param: [
    {
      type: 'React.ChangeEvent',
      name: 'event',
      description: 'Event source of the callback. You\n' +
        '        can pull out the new value by accessing `event.target.value`.'
    }
  ]
}
{
  param: [
    {
      type: 'React.FocusEvent',
      name: 'event',
      description: 'Event source of the callback.'
    }
  ]
}
{
  param: [
    {
      type: 'React.KeyboardEvent',
      name: 'event',
      description: 'Event source of the callback.'
    }
  ]
}
{
  param: [
    {
      type: 'React.KeyboardEvent',
      name: 'event',
      description: 'Event source of the callback.'
    }
  ]
}
{
  param: [
    {
      type: 'function',
      name: 'mutate',
      description: 'Function to trigger a mutation from your UI.'
    },
    {
      type: 'MutationResult',
      name: 'mutationResult',
      description: 'Results of the\n        mutation.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the\n        query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the\n        query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{}
{}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [
    { type: 'React.MouseEvent', name: 'event', description: '' },
    { type: 'boolean', name: 'opened', description: '' }
  ]
}
⠀
⠀
{
  param: [
    {
      type: 'React.ChangeEvent',
      name: 'event',
      description: 'Event source of the callback.'
    },
    {
      type: 'any',
      name: 'value',
      description: 'The value of the radio button.'
    }
  ]
}
{
  param: [
    {
      type: 'React.MouseEvent',
      name: 'event',
      description: 'Event source of the callback.'
    }
  ]
}
{
  param: [
    {
      type: 'react.ChangeEvent',
      name: 'event',
      description: 'Event source of the callback.'
    },
    {
      type: 'any',
      name: 'value',
      description: 'The value of the selected radio button.'
    }
  ]
}
⠀
{}
{}
{}
{}
{
  param: [
    { type: 'React.ChangeEvent', name: 'event', description: '' },
    { type: 'any', name: 'value', description: '' }
  ]
}
{
  param: [
    { type: 'React.MouseEvent', name: 'event', description: '' },
    { type: 'any', name: 'value', description: '' }
  ]
}
⠀
{}
{}
{}
{}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{}
{}
{
  param: [
    {
      type: 'React.MouseEvent',
      name: 'event',
      description: 'Event source of the callback.'
    },
    {
      type: 'any',
      name: 'stepValue',
      description: 'The value of the step.'
    }
  ]
}
⠀
{
  param: [ { type: 'React.ChangeEvent', name: 'event', description: '' } ]
}
⠀
{
  param: [ { type: 'Cursor', name: 'cursor', description: 'Items to load.' } ]
}
{
  param: [
    { type: 'React.ChangeEvent', name: 'event', description: '' },
    {
      type: 'SelectedCallbackArgument',
      name: 'selectedItem',
      description: ''
    }
  ]
}
{
  param: [
    { type: 'SelectedCallbackArgument', name: 'item', description: '' }
  ],
  return: [ { promiseType: undefined, type: 'boolean', description: '' } ]
}
{}
{}
{
  param: [
    { type: 'React.MouseEvent', name: 'event', description: '' },
    { type: 'Object', name: 'sortingData', description: '' }
  ]
}
{
  param: [
    { type: 'object', name: 'a', description: '' },
    { type: 'object', name: 'b', description: '' }
  ],
  return: [ { promiseType: undefined, type: 'number', description: '' } ]
}
{}
⠀
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
⠀
{
  param: [
    {
      type: 'any',
      name: 'value',
      description: 'The value of the selected tab item.'
    }
  ]
}
{
  param: [
    {
      type: 'React.FocusEvent',
      name: 'event',
      description: 'Event source of the callback.'
    }
  ]
}
{
  param: [
    {
      type: 'React.ChangeEvent',
      name: 'event',
      description: 'Event source of the callback. You\n' +
        '        can pull out the new value by accessing `event.target.value`.'
    }
  ]
}
{
  param: [
    {
      type: 'React.FocusEvent',
      name: 'event',
      description: 'Event source of the callback.'
    }
  ]
}
{
  param: [
    {
      type: 'React.KeyboardEvent',
      name: 'event',
      description: 'Event source of the callback.'
    }
  ]
}
{
  param: [
    {
      type: 'React.KeyboardEvent',
      name: 'event',
      description: 'Event source of the callback.'
    }
  ]
}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [
    {
      type: 'React.MouseEvent',
      name: 'event',
      description: 'Event source of the callback.'
    },
    {
      type: 'any',
      name: 'tileValue',
      description: 'The value of the tile.'
    },
    {
      type: 'boolean',
      name: 'checked',
      description: 'The new checked state.'
    }
  ]
}
⠀
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{}
{}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'function',
      name: 'mutate',
      description: 'Function to trigger a mutation from your UI.'
    },
    {
      type: 'MutationResult',
      name: 'mutationResult',
      description: 'Results of the\n        mutation.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [
    {
      type: 'QueryResult',
      name: 'queryResult',
      description: 'Results of the query.'
    }
  ],
  return: [
    {
      promiseType: undefined,
      type: 'React.ReactNode',
      description: ''
    }
  ]
}
{
  param: [ { type: 'React.MouseEvent', name: 'event', description: '' } ]
}
```

**Comment by jpvajda** [comment]
after loading `http://localhost:8000/` I saw this 

```
Warning: Failed prop type: The prop `duration` is marked as required in `GuideTile`, but its value is `null`.
    at GuideTile (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:62501:3)
    at IndexPage (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64176:3)
    at main
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at Main (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41501:3)
    at div
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at Layout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41449:3)
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at MainLayout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:63972:3)
    at Layout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64052:3)
    at QueryClientProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:147522:21)
    at LocaleProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41840:3)
    at I18nextProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:141110:19)
    at RouteHandler (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:176297:5)
    at div
    at FocusHandlerImpl (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64930:5)
    at FocusHandler (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64901:19)
    at RouterImpl (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64806:5)
    at Location (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64635:23)
    at Router
    at ServerLocation (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64743:19)
    at MDXProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:3052:46)
    at MDXScopeProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:60688:3)
    at /Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:60949:15
    at /Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:3035:48
Warning: Failed prop type: Invalid prop `name` of value `link` supplied to `FeatherIcon`, expected one of ["book-open","box","bar-chart","cpu","edit","external-link","copy","chevron-right","clock","github","pen","search","upload-cloud","sun","moon","x","award","trello","instagram","linkedin","twitch","twitter","users","eye","hard-drive","database"].
    at FeatherIcon (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:61813:5)
    at IndexPage (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64176:3)
    at main
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at Main (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41501:3)
    at div
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at Layout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41449:3)
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at MainLayout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:63972:3)
    at Layout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64052:3)
    at QueryClientProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:147522:21)
    at LocaleProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41840:3)
    at I18nextProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:141110:19)
    at RouteHandler (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:176297:5)
    at div
    at FocusHandlerImpl (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64930:5)
    at FocusHandler (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64901:19)
    at RouterImpl (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64806:5)
    at Location (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64635:23)
    at Router
    at ServerLocation (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64743:19)
    at MDXProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:3052:46)
    at MDXScopeProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:60688:3)
    at /Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:60949:15
    at /Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:3035:48
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <SEO>. See https://reactjs.org/link/warning-keys for more information.
    at meta
    at DevSiteSeo (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:61672:3)
    at IndexPage (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64176:3)
    at main
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at Main (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41501:3)
    at div
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at Layout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41449:3)
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at MainLayout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:63972:3)
    at Layout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64052:3)
    at QueryClientProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:147522:21)
    at LocaleProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41840:3)
    at I18nextProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:141110:19)
    at RouteHandler (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:176297:5)
    at div
    at FocusHandlerImpl (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64930:5)
    at FocusHandler (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64901:19)
    at RouterImpl (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64806:5)
    at Location (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64635:23)
    at Router
    at ServerLocation (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64743:19)
    at MDXProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:3052:46)
    at MDXScopeProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:60688:3)
    at /Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:60949:15
    at /Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:3035:48
Warning: Received `true` for a non-boolean attribute `interactive`.

If you want to write it to the DOM, pass a string instead: interactive="true" or interactive={value.toString()}.
    at a
    at Location (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64635:23)
    at Link (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:65044:24)
    at GatsbyLink (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:34463:30)
    at Location (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64635:23)
    at GatsbyLinkLocationWrapper
    at /Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41716:5
    at Surface (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at GuideTile (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:62501:3)
    at div
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at List (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:62424:3)
    at section
    at article
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at Content (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41351:3)
    at div
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at PageLayout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:62982:3)
    at IndexPage (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64176:3)
    at main
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at Main (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41501:3)
    at div
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at Layout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41449:3)
    at EmotionCssPropInternal (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:605:68)
    at MainLayout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:63972:3)
    at Layout (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64052:3)
    at QueryClientProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:147522:21)
    at LocaleProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:41840:3)
    at I18nextProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:141110:19)
    at RouteHandler (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:176297:5)
    at div
    at FocusHandlerImpl (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64930:5)
    at FocusHandler (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64901:19)
    at RouterImpl (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64806:5)
    at Location (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64635:23)
    at Router
    at ServerLocation (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:64743:19)
    at MDXProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:3052:46)
    at MDXScopeProvider (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:60688:3)
    at /Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:60949:15
    at /Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:3035:48
GATSBY_NEWRELIC_ENV env variable is not set
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <body>. See https://reactjs.org/link/warning-keys for more information.
    at script
    at HTML (/Users/jvajda/Documents/Github/DevEn/developer-website/public/render-page.js:35499:76)

```

**Comment by jpvajda** [comment]
Other then these 2 terminal errors, the site seems to render OK on `Gatsby 3.8`

**Comment by rudouglas** [comment]
That first output is actually just a stray `console.log` from the SDK, this PR should resolve it:
https://github.com/newrelic/developer-website/pull/1448

**Comment by jpvajda** [comment]
@rudouglas Nice! I can work throug the other errors and see if I an resolve them.

**Comment by rudouglas** [comment]
I also don't think they are related to `Gatsby 3.8` @jpvajda  they are in the console at the moment

**Comment by jpvajda** [comment]
@rudouglas I didn't think they were related either, but thanks for confirming. I love a clean terminal tho.. 🧹

**Comment by rudouglas** [comment]
such many samesies, get that sweepin brush out 🗑️
